env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - 
      anonymous: always
      named: never
      asyncArrow: always
  valid-typeof: 0
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: false
